### PR TITLE
add functionnal horn button and led control button

### PR DESCRIPTION
**Pull request by xWane**

### CODE REVIEW

**Comment by xWane** [comment]
can you try if it work @BenIzak ?

**Comment by BenIzak** [comment]
I've simplified websocket management, you just need to adapt your code (it'll be easier than before).

**Comment by BenIzak** [comment]
You just need to rebase from main

**Comment by xWane** [comment]
can you review this @BenIzak ? I would like you to test this, I just add automode button and emoji control button.

**Comment by BenIzak** [comment]
No problem well done @xWane

**Review by BenIzak — APPROVED** [review]

**Pull request merged**
